#!/bin/bash
conda activate wombat

OUTDIR=$(python -c "import wombat_config as cfg; print(cfg.config['output_directory'])")
OUTDIR=$(pwd OUTDIR)/Wombat_OUTPUT_`date "+%Y%m%d_%H%M%S"`

mkdir -p $OUTDIR
cp input_files.csv $OUTDIR/
cp wombat_config.py $OUTDIR/

python wombat.py $OUTDIR "$@" 2>&1 | tee $OUTDIR/wombat.log
# Run only if previous is successfully completed
if [ $? -eq 0 ]; then
    python -c "from terminal_banner import Banner; print(Banner('\nGenerating HTML report.\n'), flush=True)" "$@" 2>&1 | tee -a $OUTDIR/wombat.log
    
    FASTAMODE=$(python -c "import wombat_config as cfg; print(cfg.config['assembled_genomes'])")
    if [ $? -eq 0 ]; then
        if [ $FASTAMODE == "True" ]; then
            conda activate wombatR
            Rscript -e "rmarkdown::render('Wombat_Report_short.Rmd', params = list(directory = '$OUTDIR'), output_dir= '$OUTDIR')" "$@" 2>&1 | tee -a $OUTDIR/wombat.log
        else
            conda activate wombatR
            Rscript -e "rmarkdown::render('Wombat_Report_long.Rmd', params = list(directory = '$OUTDIR'), output_dir= '$OUTDIR')" "$@" 2>&1 | tee -a $OUTDIR/wombat.log
        fi
        
        if [ $? -eq 0 ]; then
            conda activate wombat
            python -c "from terminal_banner import Banner; print(Banner('\nDONE\n'), flush=True)" "$@" 2>&1 | tee -a $OUTDIR/wombat.log
        fi
        
        conda activate wombat

        rm $OUTDIR/wombat_config.json
        
    fi
fi